name: year_planner
description: Plan your year with a Calendar 

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


# consider running `flutter pub upgrade --major-versions`. 
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  #flutter_riverpod: ^2.1.1
  hooks_riverpod: ^2.1.2
  flutter_hooks: ^0.18.5+1
  table_calendar: ^3.0.8
  simple_gesture_detector: ^0.2.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  isar_generator: ^3.0.5
  build_runner: ^2.3.3

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

flutter_icons:
  image_path_android: "assets/icon_2.png"
  image_path_ios: "assets/icon_1.png"
  android: true 
  ios: true 
  adaptive_icon_background: "assets/icon_2_front.png"
  adaptive_icon_foreground: "assets/icon_2_back.png"
  min_sdk_android: 21
  #remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon_2.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon_2.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon_1.png"